# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_image_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.CharField(max_length=200),
        ),
    ]
