# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190515_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
