# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190518_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
