# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_profile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='poster_id',
            field=models.IntegerField(default=0),
        ),
    ]
