# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_image_poster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_message',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
