# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190528_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.IntegerField(default=0),
        ),
    ]
